name: Update Swagger UI
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
    inputs:
      yaml_files:
        description: 'Comma-separated list of YAML files (optional)'
        required: false
        default: 'omwApi.yml,testApi.yml'

jobs:
  updateSwagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Latest Swagger UI Release
        id: swagger-ui
        run: |
          release_tag=$(curl -sL https://api.github.com/repos/swagger-api/swagger-ui/releases/latest | jq -r ".tag_name")
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
          current_tag=$(<swagger-ui.version)
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT
      - name: Update Swagger UI
        if: steps.swagger-ui.outputs.current_tag != steps.swagger-ui.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.swagger-ui.outputs.release_tag }}
          SWAGGER_YAMLS: ${{ github.event.inputs.yaml_files || 'omwApi.yml,testApi.yml' }}
        run: |
          # Delete the dist directory and index.html
          rm -fr dist index.html
          # Download the release
          curl -sL -o $RELEASE_TAG https://api.github.com/repos/swagger-api/swagger-ui/tarball/$RELEASE_TAG
          # Extract the dist directory
          tar -xzf $RELEASE_TAG --strip-components=1 $(tar -tzf $RELEASE_TAG | head -1 | cut -f1 -d"/")/dist
          rm $RELEASE_TAG
          # Move index.html to the root
          mv dist/index.html .
          
          # Build the URLs array for multiple APIs
          IFS=',' read -ra YAML_FILES <<< "$SWAGGER_YAMLS"
          URLS_ARRAY="["
          for i in "${!YAML_FILES[@]}"; do
            yaml_file=$(echo "${YAML_FILES[$i]}" | xargs)
            api_name=$(basename "$yaml_file" .yml)
            # Create a display name (remove "Api" suffix and add spaces before capitals)
            display_name=$(echo "$api_name" | sed 's/Api$//' | sed 's/\([A-Z]\)/ \1/g' | sed 's/^ //')
          
            if [ $i -gt 0 ]; then URLS_ARRAY+=","; fi
            URLS_ARRAY+="{\"url\":\"$yaml_file\",\"name\":\"$display_name\"}"
          done
          URLS_ARRAY+="]"
          
          # Create swagger-initializer.js with multiple URLs
          cat > dist/swagger-initializer.js << EOF
          window.onload = function() {
            window.ui = SwaggerUIBundle({
              urls: $URLS_ARRAY,
              dom_id: '#swagger-ui',
              deepLinking: true,
              presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
              ],
              plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
              ],
              layout: "StandaloneLayout"
            });
          };
          EOF
          
          # Fix references in index.html
          sed -i "s|href=\"./|href=\"dist/|g" index.html
          sed -i "s|src=\"./|src=\"dist/|g" index.html
          sed -i "s|href=\"index|href=\"dist/index|g" index.html
          # Update current release
          echo ${{ steps.swagger-ui.outputs.release_tag }} > swagger-ui.version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update swagger-ui to ${{ steps.swagger-ui.outputs.release_tag }}
          title: Update SwaggerUI to ${{ steps.swagger-ui.outputs.release_tag }}
          body: |
            Updates [swagger-ui][1] to ${{ steps.swagger-ui.outputs.release_tag }}
            
            APIs included: ${{ env.SWAGGER_YAMLS }}

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/swagger-api/swagger-ui
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: swagger-ui-updates
